/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import SceneSprite from "./game/SceneSprite"
import MainView from "./game/views/MainView"
import MenuView from "./game/views/MenuView"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=560;
    static height:number=960;
    static scaleMode:string="showall";
    static screenMode:string="horizontal";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="views/MainUI.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("game/SceneSprite.ts",SceneSprite);
        reg("game/views/MainView.ts",MainView);
        reg("game/views/MenuView.ts",MenuView);
    }
}
GameConfig.init();